### ISSUE TITLE
Game crashes when playback completes

### ISSUE THREAD

**Issue by jeffstienstra** [mchorse/mchorse.github.io#2]
Hello...its me...again :)
I've had a problem with MC 1.10.2 crashing once playback of a recording completes.  If I use my playback control to stop the recording before completion everything works fine.  I'm sure this must be a problem with my setup and not the mod.

**Minecraft version 1.10.2**

**Mods I am using:**
BetterFoliage-MC1.10-2.1.1
blockbuster-1.4.5-1.10.2
MrCrayfish furniture mod 4.1.1
ItemPhysic-Mod-Lite-1.10.2
metamorph-1.0.2-1.10.2
OptiFine-1.10.2_HD_U_D1
ShoulderSurfing-1.10.2-1.9.4-1.9-1.2
TickrateChanger-1.0.8

**Here is my crash report:**

---- Minecraft Crash Report ----

WARNING: coremods are present:
  ShoulderPlugin (ShoulderSurfing-1.10.2-1.9.4-1.9-1.2.jar)
  ItemPatchingLoader (ItemPhysic-Mod-Lite-1.10.2.jar)
  TickrateChanger (TickrateChanger-1.0.8.jar)
  BetterFoliageLoader (BetterFoliage-MC1.10-2.1.1.jar)
Contact their authors BEFORE contacting forge

// Would you like a cupcake?

Time: 1/27/17 9:24 AM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at mchorse.blockbuster.recording.data.Record.resetMount(Record.java:169)
	at mchorse.blockbuster.recording.data.Record.reset(Record.java:131)
	at mchorse.blockbuster.recording.RecordManager.stopPlayback(RecordManager.java:173)
	at mchorse.blockbuster.common.entity.EntityActor.func_70636_d(EntityActor.java:211)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2020)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:384)
	at net.minecraft.entity.Entity.func_70098_U(Entity.java:1848)
	at net.minecraft.entity.EntityLivingBase.func_70098_U(EntityLivingBase.java:2300)
	at net.minecraft.world.World.func_72866_a(World.java:1958)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:837)
	at net.minecraft.world.World.func_72870_g(World.java:1932)
	at net.minecraft.world.World.func_72866_a(World.java:2022)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:837)
	at net.minecraft.world.World.func_72870_g(World.java:1932)
	at net.minecraft.world.World.func_72939_s(World.java:1748)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at mchorse.blockbuster.recording.data.Record.resetMount(Record.java:169)
	at mchorse.blockbuster.recording.data.Record.reset(Record.java:131)
	at mchorse.blockbuster.recording.RecordManager.stopPlayback(RecordManager.java:173)
	at mchorse.blockbuster.common.entity.EntityActor.func_70636_d(EntityActor.java:211)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2020)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:384)
	at net.minecraft.entity.Entity.func_70098_U(Entity.java:1848)
	at net.minecraft.entity.EntityLivingBase.func_70098_U(EntityLivingBase.java:2300)
	at net.minecraft.world.World.func_72866_a(World.java:1958)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:837)
	at net.minecraft.world.World.func_72870_g(World.java:1932)
	at net.minecraft.world.World.func_72866_a(World.java:2022)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:837)
	at net.minecraft.world.World.func_72870_g(World.java:1932)

-- Entity being ticked --
Details:
	Entity Type: MinecartRideable (net.minecraft.entity.item.EntityMinecartEmpty)
	Entity ID: 54
	Entity Name: entity.MinecartRideable.name
	Entity's Exact location: -15.50, 4.00, 57.45
	Entity's Block location: World: (-16,4,57), Chunk: (at 0,0,9 in -1,3; contains blocks -16,0,48 to -1,255,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1748)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618)

-- Affected level --
Details:
	Level name: green screen
	All players: 1 total; [EntityPlayerMP['Sir_Knightynight'/53, l='green screen', x=-12.00, y=4.00, z=53.90]]
	Chunk stats: ServerChunkCache: 1625 Drop: 0
	Level seed: 7538446512934677329
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (221,4,1510), Chunk: (at 13,0,6 in 13,94; contains blocks 208,0,1504 to 223,255,1519), Region: (0,2; contains chunks 0,64 to 31,95, blocks 0,0,1024 to 511,255,1535)
	Level time: 69974 game time, 6000 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 29113 (now: false), thunder time: 44862 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 319276984 bytes (304 MB) / 871718912 bytes (831 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.1.2011 Optifine OptiFine_1.10.2_HD_U_D1 10 mods loaded, 10 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.1.2011.jar) 
	UCHIJAAAA	Forge{12.18.1.2011} [Minecraft Forge] (forge-1.10.2-12.18.1.2011.jar) 
	UCHIJAAAA	itemphysic{1.3.0} [ItemPhysic] (minecraft.jar) 
	UCHIJAAAA	BetterFoliage{2.1.1} [Better Foliage] (BetterFoliage-MC1.10-2.1.1.jar) 
	UCHIJAAAA	blockbuster{1.4.5} [Blockbuster] (blockbuster-1.4.5-1.10.2.jar) 
	UCHIJAAAA	cfm{4.1} [MrCrayfish's Furniture Mod] (furniture mod MrCrayfish1.10.2.jar) 
	UCHIJAAAA	metamorph{1.0.2} [Metamorph] (metamorph-1.0.2-1.10.2.jar) 
	UCHIJAAAA	shouldersurfing{1.2} [Shoulder Surfing] (ShoulderSurfing-1.10.2-1.9.4-1.9-1.2.jar) 
	UCHIJAAAA	tickratechanger{1.0.8} [Tickrate Changer] (TickrateChanger-1.0.8.jar) 
	Loaded coremods (and transformers): 
ShoulderPlugin (ShoulderSurfing-1.10.2-1.9.4-1.9-1.2.jar)
  com.teamderpy.shouldersurfing.asm.ShoulderTransformations
ItemPatchingLoader (ItemPhysic-Mod-Lite-1.10.2.jar)
  com.creativemd.itemphysic.ItemTransformer
TickrateChanger (TickrateChanger-1.0.8.jar)
  me.guichaguri.tickratechanger.TickrateTransformer
BetterFoliageLoader (BetterFoliage-MC1.10-2.1.1.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Sir_Knightynight'/53, l='green screen', x=-12.00, y=4.00, z=53.90]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.10.2_HD_U_D1
	Render Distance Chunks: 18
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 369.09
	OpenGlRenderer: GeForce GTX 960/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

If this is something you can address, I'd be thrilled.  If not, I'll keep trying mod combos until something works.  Thanks!

Sir_KnightyNight

**Comment by mchorse** [comment]
@Sir-KnightyNight, oh yeah, I'm already acknowledged of this bug, and it's already fixed in the dev branch. Thanks for reporting, though! 😃 

P.S.: To be honest, this is the wrong repository for posting issues for Blockbuster. Blockbuster's issue tracker lives [here](https://github.com/mchorse/blockbuster) 😄
